version: "3.7"

networks:
  default:
    driver: bridge

services:
  tasks:
    image: tasks
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: tasks
    restart: always
    env_file:
      - .dockerenv
    command:
      "poetry run python main.py"